// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgvygiWkhm6e4wyh8ssU5OJsGerQEBYw',
    appId: '1:28029805652:web:ba2ef5f8683397a95a39c1',
    messagingSenderId: '28029805652',
    projectId: 'fluttertp3-87ba7',
    authDomain: 'fluttertp3-87ba7.firebaseapp.com',
    storageBucket: 'fluttertp3-87ba7.firebasestorage.app',
    measurementId: 'G-4RVQESQD8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RKlmbSgvYxkn1Kl3GKtYx12JA2dozeQ',
    appId: '1:28029805652:android:89ef64b285e068f05a39c1',
    messagingSenderId: '28029805652',
    projectId: 'fluttertp3-87ba7',
    storageBucket: 'fluttertp3-87ba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItFncuZQvAYyW3q4_W5t--4u70rQAJTE',
    appId: '1:28029805652:ios:2c003923fae380bc5a39c1',
    messagingSenderId: '28029805652',
    projectId: 'fluttertp3-87ba7',
    storageBucket: 'fluttertp3-87ba7.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCItFncuZQvAYyW3q4_W5t--4u70rQAJTE',
    appId: '1:28029805652:ios:2c003923fae380bc5a39c1',
    messagingSenderId: '28029805652',
    projectId: 'fluttertp3-87ba7',
    storageBucket: 'fluttertp3-87ba7.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARgvygiWkhm6e4wyh8ssU5OJsGerQEBYw',
    appId: '1:28029805652:web:f520cd388d343c8a5a39c1',
    messagingSenderId: '28029805652',
    projectId: 'fluttertp3-87ba7',
    authDomain: 'fluttertp3-87ba7.firebaseapp.com',
    storageBucket: 'fluttertp3-87ba7.firebasestorage.app',
    measurementId: 'G-LFC9NTQNKJ',
  );
}
